config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create]
  get "login" => "sessions#new", as: :login
  get "logout" => "sessions#destroy", as: :logout
  resources :toots, only: [:create] do
    resources :favorites, only: [:create]
  end
  resources :users, only: [:index, :show, :new, :create] do
    resources :followers, only: [:index, :create, :destroy]
    resources :followings, only: [:index]
    resources :mentions, only: [:index]
  end
  get "sign_up" => "users#new", as: :sign_up

  namespace :api do
    namespace :v1 do
      resource :sessions, only: [:create]
      post "login" => "sessions#create"
      resources :toots, only: [:index, :create]
      resources :users, only: [:index, :show]
    end
  end

  root 'users#index'
end

app/models/create_toot_use_case.rb
class CreateTootUseCase
  def self.run(user, params)
    toot = user.toots.build(params)
    if toot.save
      mentioned_users(toot).each do |mentioned_user|
        mentioned_user.mentions.create(toot: toot)
      end
    end
    toot
  end

  private

  def self.mentioned_users(toot)
    matches = toot.body.scan(/@(\w*)/).flatten

    matches.map do |match|
      User.find_by(username: match)
    end.compact
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :toot

  validates :user_id, presence: true
  validates :toot_id, presence: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  belongs_to :user
  belongs_to :toot
end

app/models/toot.rb
class Toot < ActiveRecord::Base
  belongs_to :user
  has_many :favorites

  validates :body, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

  scope :ordered, lambda { order("created_at desc") }
  
  def self.all_ordered
    Toot.all.ordered
  end

  def self.only_for(user)
    Toot.where(user: user).ordered
  end

  def favorite_for?(user)
    if favorites.find_by(user_id: user.id)
      true
    else
      false
    end
  end

  def favorite_count
    favorites.size
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_secure_token :auth_token

  validates :first_name, presence: true, allow_blank: false
  validates :username, presence: true, allow_blank: false
  validates :password, presence: true, allow_blank: false, confirmation: true, on: :create
  validates :password_confirmation, presence: true, on: :create
                        
  has_many :toots
  has_many :follower_users, class_name: "Follow", foreign_key: "followed_id"
  has_many :followed_users, class_name: "Follow", foreign_key: "follower_id"
  has_many :followers, through: :follower_users
  has_many :followeds, through: :followed_users
  has_many :favorites
  has_many :mentions

  def feed
    Toot.where("user_id = ? or user_id in (?)", id, following_ids).order("created_at desc")
  end

  def following?(other_user)
    self.followeds.include?(other_user)
  end

  def follow!(other_user)
    followeds << other_user
  end

  def unfollow!(other_user)
    followed_users.find_by(followed_id: other_user.id).destroy
  end

  private

  def following_ids
    followeds.pluck("id")
  end
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def default_serializer_options
    {root: false}
  end

  def authenticate_with_token
    authenticate_or_request_with_http_token do |token, options|
      @user = User.find_by(auth_token: token)
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Api::V1::ApiController
  def create
    authenticate_or_request_with_http_basic do |username, password|
      @user = User.find_by(username: username.downcase)
      if @user && @user.authenticate(password)
        render json: @user, serializer: UserSerializerWithToken, status: 200
      else
        render json: {}, status: 401
      end
    end
  end
end

app/controllers/api/v1/toots_controller.rb
class Api::V1::TootsController < Api::V1::ApiController
  before_filter :authenticate_with_token

  def index
    @toots = @user.feed
    render json: @toots, each_serializer: TootSerializer, status: 200
  end

  def create
    @toot = @user.toots.build(toot_params)
    if @toot.save
      render json: @toot, status: 200
    else
      render json: @toot.errors, status: :unprocessable_entity
    end
  end

  private

  def toot_params
    ActiveModelSerializers::Deserialization.jsonapi_parse(params, only: [:body])
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApiController
  before_filter :authenticate_with_token

  def index
    @users = User.all
    render json: @users, each_serializer: UserSerializer, status: 200
  end

  def show
    @user = User.find(params[:id])
    render json: @user, status: 200
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    @current_user || User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def sign_in(user)
    session[:user_id] = user.id
  end
  helper_method :sign_in
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @toot = Toot.find(params[:toot_id])
    @toot.favorites.create(user: current_user)
    redirect_to request.referer
  end

  private

  def favorites_params
    params.permit(:toot_id)
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @followers = @user.followers 
  end

  def create
    @target_user = User.find(params[:user_id])
    current_user.follow!(@target_user)
    redirect_to user_path(params[:user_id])
  end
  
  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow!(@user)
    redirect_to user_path(params[:user_id])
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @followings = @user.followeds
  end
end

app/controllers/mentions_controller.rb
class MentionsController < ApplicationController
  def index
    @mentions = Mention.includes(:toot).where(user_id: params[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username].downcase) 
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to login_path, notice: "Invalid username or password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out successfully"
  end
end

app/controllers/toots_controller.rb
class TootsController < ApplicationController
  def create
    @toot = CreateTootUseCase.run(current_user, toot_parameters)
    if @toot.save
      redirect_to user_path(current_user)
    else
      redirect_to root_path, alert: @toot.errors
    end
  end

  private

  def toot_parameters
    params.require(:toot).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @toots = Toot.all_ordered
  end

  def show
    @user = User.find(params[:id])
    if current_user == @user
      toots = @user.feed
    else
      toots = Toot.only_for(@user) 
    end
    @toots = toots.map { |toot| TootPresenter.new(toot) }
  end

  def new
  end

  def create
    @user = User.new(user_parameters)
    if @user.save
      sign_in(@user)
      redirect_to root_path
    else
      render "new", alert: @user.errors
    end
  end

  private

  def user_parameters
    params.require(:user).permit(:first_name, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/followers/index.html.erb
<div class="row">
  <div class="col-md-3">
    <h2><%= "#{@user.first_name}'s User Profile" %></h2>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= link_to "Sniffers", user_followers_path(@user) %>
      </div>
      <div class="panel-body">
        <%= link_to "Smelling", user_followings_path(@user) %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <% if current_user %>
      <div class="row">
        <div class="panel panel-defult">
          <div class="panel-body">
            <%= form_for :toot, url: toots_path, class: "navbar-form navbar-left" do |f| %>
              <%= f.label "Enter your Toot:" %>
              <%= f.text_area :body, class: "form-control" %>
              <%= f.submit "Submit", class: "btn btn-default"  %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="followers">
        <% @followers.each do |follower| %>
          <div class="panel panel-default">
            <div class="panel-body">
              <h4><%= link_to follower.first_name, user_path(follower) %></h4>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/followings/index.html.erb
<div class="row">
  <div class="col-md-3">
    <h2><%= "#{@user.first_name}'s User Profile" %></h2>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= link_to "Sniffers", user_followers_path(@user) %>
      </div>
      <div class="panel-body">
        <%= link_to "Smelling", user_followings_path(@user) %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <% if current_user %>
      <div class="row">
        <div class="panel panel-defult">
          <div class="panel-body">
            <%= form_for :toot, url: toots_path, class: "navbar-form navbar-left" do |f| %>
              <%= f.label "Enter your Toot:" %>
              <%= f.text_area :body, class: "form-control" %>
              <%= f.submit "Submit", class: "btn btn-default"  %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="following">
        <% @followings.each do |following| %>
          <div class="panel panel-default">
            <div class="panel-body">
              <h4><%= link_to following.first_name, user_path(following) %></h4>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tooter</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Tooter</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <% if current_user %> 
            <li><%= link_to "My Toot Stream", user_path(current_user) %></li>
            <li><%= link_to "Logout", logout_path %></li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
            <li><%= link_to "Register", sign_up_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container-fluid">
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </div>     
</body>
</html>

app/views/mentions/index.html.erb
<div class="mentions">
  <% @mentions.each do |mention| %>
    <div class="toot"><%= mention.toot.body %></div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-3">
    <% if current_user %>
      <h2><%= "Welcome #{current_user.first_name}!" %></h2>
      <div class="panel panel-default">
        <div class="panel-body">
          <%= link_to "Sniffers", user_followers_path(current_user) %>
        </div>
        <div class="panel-body">
          <%= link_to "Smelling", user_followings_path(current_user) %>
        </div>
        <div class="panel-body">
          <%= link_to "Mentions", user_mentions_path(current_user) %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <% if current_user %>
      <div class="row">
        <div class="panel panel-defult">
          <div class="panel-body">
            <%= form_for :toot, url: toots_path, class: "navbar-form navbar-left" do |f| %>
              <%= f.label "Enter your Toot:" %>
              <%= f.text_area :body, class: "form-control" %>
              <%= f.submit "Submit", class: "btn btn-default"  %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <h2>All Toots</h2>
    <div class="row">
      <div class="toots">
        <% @toots.each do |toot| %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4><%= link_to toot.user.username, user_path(toot.user) %> - <small>Tooted at: <%= toot.created_at.to_formatted_s(:short) %></small></h4>
            </div>
            <div class="panel-body">
              <%= toot.body %> 
              <div style="float:right">
                <% if current_user %>
                  <% if toot.favorite_for?(current_user) %>
                    Favorited!
                  <% else %>
                    <%= link_to "Favorite", toot_favorites_path(toot), { method: :post } %>
                  <% end %>
                <% end %>
                | Favorited <%= toot.favorite_count %> times
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-3">
    <h2>Register</h2>
  </div>
  <div class="col-md-6">
    <div class="row">
      <%= form_for :user, url: users_path, class: "navbar-form navbar-left" do |f| %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control" %>
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %>
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
        <%= f.submit "Submit", class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <h2><%= "#{@user.first_name}'s User Profile" %></h2>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= link_to "Sniffers", user_followers_path(@user) %>
      </div>
      <div class="panel-body">
        <%= link_to "Smelling", user_followings_path(@user) %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <% if current_user && current_user == @user %>
      <div class="row">
        <div class="panel panel-defult">
          <div class="panel-body">
            <%= form_for :toot, url: toots_path, class: "navbar-form navbar-left" do |f| %>
              <%= f.label "Enter your Toot:" %>
              <%= f.text_area :body, class: "form-control" %>
              <%= f.submit "Submit", class: "btn btn-default"  %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <% if current_user.following?(@user) %>
      <%= link_to "Stop sniffing", user_follower_path(@user, current_user), { method: :delete } %>
    <% elsif current_user != @user %>
      <%= link_to "Sniff", user_followers_path(@user), { method: :post } %>
    <% end %>
    <div class="row">
      <div class="toots">
        <% @toots.each do |toot| %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4><%= link_to toot.user.username, user_path(toot.user) %> - <small>Tooted at: <%= toot.created_at.to_formatted_s(:short) %></small></h4>
            </div>
            <div class="panel-body">
              <%= toot.body_with_links %> 
              <div style="float:right">
                <% if current_user %>
                  <% if toot.favorite_for?(current_user) %>
                    Favorited!
                  <% else %>
                    <%= link_to "Favorite", toot_favorites_path(toot), { method: :post } %>
                  <% end %>
                <% end %>
                | Favorited <%= toot.favorite_count %> times
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>